# Generated by Django 4.1.5 on 2023-01-11 06:55

import coplate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0002_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임 입니다'}, max_length=15, null=True, unique=True, validators=[coplate.validators.validate_no_special_characters]),
        ),
    ]
